# Generated by Django 4.2.15 on 2024-08-21 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cartitem_product_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
